FROM python:3.7-stretch
# Maintainer of image
LABEL maintainer="tidianefofana18@gmail.com"

# Install of dependencies
RUN apt-get update -y && apt-get install python-dev python3-dev libsasl2-dev python-dev libldap2-dev libssl
RUN pip install --upgrade pip
RUN pip install flask flask_httpauth flask_simpleldap python-dotenv
RUN pip install numpy
RUN pip install pyqt5
RUN pip install playsound
RUN pip install keras
RUN pip install tensorflow gpu=2.2
RUN pip install pywin32
RUN pip install opencv-contrib-python
RUN pip install sklearn
RUN pip install tflearn
#cCOPY SOURCE CODE IN THE IMAGE
COPY app.py /

# CREATE DATA FOLDER
VOLUME [ "/data" ]

# EXPOSE PORT
EXPOSE 5001

# RUN CODE
CMD [ "python", "./app.py" ]